import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${inter.className}`}
        style={{
          background: "linear-gradient(to bottom, #FFFFFF 0%, #5420A4 100%)",
        }}
      >
        {children}
      </body>
    </html>
  );
}
